# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d7282979b7cb173b4e46e28484884dfc1e19b4ed45b23d51919162a637ee99a5013de455177b15c9c569d24f2d216d9c95e5814a6010fe8247f2f9950979d0

test:
  secret_key_base: 2e82415a386a317b2a7376c9a23e487ef494b6dd62de318aba0d81ddd8aa61584e1c252c9c210078e40d3a8a25db391aa0fb45a7907a321d83ff44dce3f28422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
